### ISSUE TITLE
Overflowed by pixels issue

### ISSUE THREAD

**Issue by YRlp98** [XeniacDev/FoxholeArtillery-mobile#1]
This app is not responsive and in devices with a smaller screen, the user will face overflowed by pixels issue.

**Comment by YRlp98** [comment]
> This app is not responsive and in devices with a smaller screen, the user will face overflowed by pixels issue.

I will fix it soon.

**Comment by mediv0** [comment]
> > This app is not responsive and in devices with a smaller screen, the user will face overflowed by pixels issue.
> 
> I will fix it soon.

Thank you
